DELETE FROM BOOK_AUTHORS;
DELETE FROM BOOK;
DELETE FROM AUTHOR;


INSERT INTO BOOK VALUES (2, 'Spring in action');
INSERT INTO BOOK VALUES (3, 'Hibernate in action');

INSERT INTO AUTHOR VALUES (3, 'Christian Bauer');

